from app.models import db, Item, Review, User, environment, SCHEMA
from random import randint

# Adds a review
def seed_reviews():
    items = Item.query.all()
    users = User.query.all()
    buyer_id = 1
    for i in range(len(items)):
        buyer_id += 1
        if buyer_id > len(users):
            buyer_id = 1
        while buyer_id == items[i].seller_id:
            buyer_id = randint(0,len(users))
        review = Review(
            buyer_id = buyer_id,
            item_id = items[i].id,
            review_body = f"This is autogenerated review #{i}",
            stars = i % 5
        )

        db.session.add(review)

    db.session.commit()


# Uses a raw SQL query to TRUNCATE or DELETE the users table. SQLAlchemy doesn't
# have a built in function to do this. With postgres in production TRUNCATE
# removes all the data from the table, and RESET IDENTITY resets the auto
# incrementing primary key, CASCADE deletes any dependent entities.  With
# sqlite3 in development you need to instead use DELETE to remove all data and
# it will reset the primary keys for you as well.
def undo_reviews():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.reviews RESTART IDENTITY CASCADE;")
    else:
        db.session.execute("DELETE FROM reviews")

    db.session.commit()
