from app.models import db, Item, Review, environment, SCHEMA


# Adds a review
def seed_reviews():
    items = Item.query.all()
    for i in range(len(items)):
        review = Review(
            user_id = items[i].user_id,
            item_id = items[i].id,
            review_body = f"This is autogenerated review #{i}"
        )

        db.session.add(review)

    db.session.commit()


# Uses a raw SQL query to TRUNCATE or DELETE the users table. SQLAlchemy doesn't
# have a built in function to do this. With postgres in production TRUNCATE
# removes all the data from the table, and RESET IDENTITY resets the auto
# incrementing primary key, CASCADE deletes any dependent entities.  With
# sqlite3 in development you need to instead use DELETE to remove all data and
# it will reset the primary keys for you as well.
def undo_reviews():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.reviews RESTART IDENTITY CASCADE;")
    else:
        db.session.execute("DELETE FROM reviews")

    db.session.commit()
